import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import process from 'node:process' // 👈 this blows up! 💣
// import process from 'process' // 👈 this works just fine. 👌

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Next.js</a> + <a href="https://nodejs.org/api/esm.html#node-imports">node protocol</a> bug
        </h1>

        <p className={styles.description}>
          Example of how using <code className={styles.code}>node:</code> in imports makes Next.js unhappy. 😞
        </p>
        <p>
          This should display the <code className={styles.code}>process.env.hello</code> environemnt variable: {`${process.env.hello}`}
        </p>
      </main>
    </div>
  )
}
